spring.config.import=optional:file:.env[.properties]
server.port=8081

spring.application.name=capability

spring.r2dbc.url=${DB_URL}
spring.r2dbc.username=${DB_USERNAME}
spring.r2dbc.password=${DB_PASSWORD}

spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema.sql

technology.base-url=${TECHNOLOGY_SERVICE_BASE_URL}